name: Windows/Linux + Python [3.8-3.11] .
on: [push]
#  push:
#    tags:
#      - "v*"
jobs:
  build_and_archive:
    name: "${{ matrix.os }} Python ${{ matrix.python-version }}"
    runs-on: "${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest", "ubuntu-latest"]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install "setuptools>=67.2.0"
          pip install wheel build
      - name: Build
        run: |
          python -m build --wheel
      - name: Archive Wheels in dist/*.whl
        uses: actions/upload-artifact@v3
        with:
          name: dist-wheels-all
          path: |
            dist
            !dist/**/*.md
      - name: Install and Test Cython
        run: |
          pip install opencv-contrib-python
          pip install git+https://github.com/rathaumons/torchreid-for-pyppbox.git
          pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
          cd pyppbox_torchreid/metrics/rank_cylib
          python test_cython.py
