name: Test Build Python [3.8-3.11]

on: [workflow_dispatch]

jobs:

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["windows-latest", "ubuntu-latest", "macos-latest"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install cibuildwheel
        run: |
          python -m pip install --upgrade pip
          python -m pip install cibuildwheel==2.14.1
      - name: Build wheels
        run: |
          python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "cp38-* cp39-* cp310-* cp311-*"
          CIBW_SKIP: "*-win32 *-manylinux_i686 *-manylinux_2_5_x86_64 *-manylinux1_x86_64"
          CIBW_ARCHS_WINDOWS: "AMD64"
          CIBW_ARCHS_LINUX: "x86_64"
          CIBW_ARCHS_MACOS: "x86_64 universal2"
      - name: Archive wheels
        uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  build_source:
    name: Build source distribution .tar.gz
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install "setuptools>=67.2.0"
          pip install wheel build
      - name: Build .tar.gz
        run: |
          python -m build --sdist
      - name: Archive .tar.gz
        uses: actions/upload-artifact@v3
        with:
          path: dist/*.tar.gz
